spring:
  application:
    name: customer-service
  data:
    mongodb:
      username: micro_service_mongo_app
      password: micro_service_mongo_app_password
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090